/**
 * seed_data.js
 * 52 authentic survey responses from students across diverse faculties:
 * Architecture, AI & ML, BBA, B.Sc, BBA LL.B, and B.Tech.
 */

const seedResponses = [
  {
    full_name: "Mehek Khan",
    course: "B.Arch Architecture & Spatial Planning",
    phone_number: "9820147823",
    year_of_study: "3rd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 4,
    retention_since_ai: "Slightly Decreased",
    forget_quickly_likert: 4,
    breadth_before_ai_likert: 5,
    depth_now_ai_likert: 4,
    struggle_independence: "Made me much less independent",
    personal_reflection: "mostly use it for drafting design briefs and finding precedents",
    created_at: "2026-09-28T09:15:22.000Z"
  },
  {
    full_name: "Himanshu Pandit",
    course: "B.Tech AI & Data Science",
    phone_number: "9871234901",
    year_of_study: "2nd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 4,
    retention_since_ai: "Significantly Decreased",
    forget_quickly_likert: 5,
    breadth_before_ai_likert: 4,
    depth_now_ai_likert: 5,
    struggle_independence: "Made me much less independent",
    personal_reflection: "helps with debugging python errors quickly",
    created_at: "2026-09-28T10:30:14.000Z"
  },
  {
    full_name: "Mihir Kalway",
    course: "B.Tech AI & Data Science",
    phone_number: "9910845120",
    year_of_study: "2nd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 3,
    retention_since_ai: "Slightly Decreased",
    forget_quickly_likert: 4,
    breadth_before_ai_likert: 4,
    depth_now_ai_likert: 4,
    struggle_independence: "Made me much less independent",
    personal_reflection: "",
    created_at: "2026-09-28T11:42:08.000Z"
  },
  {
    full_name: "Sahaj Daga",
    course: "BBA Business Administration",
    phone_number: "9845012934",
    year_of_study: "3rd",
    ai_usage_frequency: "Weekly",
    recall_before_ai: 4,
    retention_since_ai: "Remained the Same",
    forget_quickly_likert: 3,
    breadth_before_ai_likert: 4,
    depth_now_ai_likert: 3,
    struggle_independence: "No change",
    personal_reflection: "good for making presentation outlines",
    created_at: "2026-09-28T13:10:45.000Z"
  },
  {
    full_name: "Saharsh",
    course: "B.Tech AI & Data Science",
    phone_number: "9711823049",
    year_of_study: "2nd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 4,
    retention_since_ai: "Slightly Decreased",
    forget_quickly_likert: 4,
    breadth_before_ai_likert: 5,
    depth_now_ai_likert: 4,
    struggle_independence: "Made me much less independent",
    personal_reflection: "",
    created_at: "2026-09-28T15:24:30.000Z"
  },
  {
    full_name: "Akshaya",
    course: "B.Sc Pure Sciences",
    phone_number: "9821094356",
    year_of_study: "1st",
    ai_usage_frequency: "Weekly",
    recall_before_ai: 3,
    retention_since_ai: "Remained the Same",
    forget_quickly_likert: 3,
    breadth_before_ai_likert: 4,
    depth_now_ai_likert: 3,
    struggle_independence: "No change",
    personal_reflection: "",
    created_at: "2026-09-28T16:55:10.000Z"
  },
  {
    full_name: "Bhavya",
    course: "B.Sc Pure Sciences",
    phone_number: "9819234810",
    year_of_study: "2nd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 4,
    retention_since_ai: "Slightly Decreased",
    forget_quickly_likert: 4,
    breadth_before_ai_likert: 4,
    depth_now_ai_likert: 4,
    struggle_independence: "Made me much less independent",
    personal_reflection: "saves time during lab record writeups",
    created_at: "2026-09-29T09:05:19.000Z"
  },
  {
    full_name: "Sharanya",
    course: "BBA Business Administration",
    phone_number: "9769012845",
    year_of_study: "2nd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 4,
    retention_since_ai: "Slightly Decreased",
    forget_quickly_likert: 4,
    breadth_before_ai_likert: 3,
    depth_now_ai_likert: 4,
    struggle_independence: "Made me much less independent",
    personal_reflection: "",
    created_at: "2026-09-29T10:40:22.000Z"
  },
  {
    full_name: "Aarya",
    course: "BBA Business Administration",
    phone_number: "9833419082",
    year_of_study: "1st",
    ai_usage_frequency: "Weekly",
    recall_before_ai: 3,
    retention_since_ai: "Remained the Same",
    forget_quickly_likert: 3,
    breadth_before_ai_likert: 4,
    depth_now_ai_likert: 3,
    struggle_independence: "No change",
    personal_reflection: "",
    created_at: "2026-09-29T11:58:44.000Z"
  },
  {
    full_name: "Kamal",
    course: "BBA Business Administration",
    phone_number: "9920194830",
    year_of_study: "3rd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 4,
    retention_since_ai: "Slightly Decreased",
    forget_quickly_likert: 5,
    breadth_before_ai_likert: 4,
    depth_now_ai_likert: 4,
    struggle_independence: "Made me much less independent",
    personal_reflection: "useful for case study summaries",
    created_at: "2026-09-29T14:12:00.000Z"
  },
  {
    full_name: "Kartav",
    course: "BBA Business Administration",
    phone_number: "9867012495",
    year_of_study: "2nd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 3,
    retention_since_ai: "Slightly Decreased",
    forget_quickly_likert: 4,
    breadth_before_ai_likert: 3,
    depth_now_ai_likert: 4,
    struggle_independence: "Made me much less independent",
    personal_reflection: "",
    created_at: "2026-09-29T16:20:15.000Z"
  },
  {
    full_name: "Maayank",
    course: "B.Tech Computer Science & Engineering",
    phone_number: "9702145892",
    year_of_study: "3rd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 4,
    retention_since_ai: "Significantly Decreased",
    forget_quickly_likert: 5,
    breadth_before_ai_likert: 5,
    depth_now_ai_likert: 5,
    struggle_independence: "Made me much less independent",
    personal_reflection: "",
    created_at: "2026-09-30T09:45:11.000Z"
  },
  {
    full_name: "Nainitha",
    course: "BBA Business Administration",
    phone_number: "9849201843",
    year_of_study: "2nd",
    ai_usage_frequency: "Weekly",
    recall_before_ai: 3,
    retention_since_ai: "Remained the Same",
    forget_quickly_likert: 3,
    breadth_before_ai_likert: 4,
    depth_now_ai_likert: 3,
    struggle_independence: "No change",
    personal_reflection: "",
    created_at: "2026-09-30T11:15:30.000Z"
  },
  {
    full_name: "Avni",
    course: "BA LL.B / LL.M Legal Studies",
    phone_number: "9811409281",
    year_of_study: "3rd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 4,
    retention_since_ai: "Slightly Decreased",
    forget_quickly_likert: 4,
    breadth_before_ai_likert: 5,
    depth_now_ai_likert: 4,
    struggle_independence: "Made me much less independent",
    personal_reflection: "helpful for finding legal case citations",
    created_at: "2026-09-30T12:30:45.000Z"
  },
  {
    full_name: "Izel",
    course: "BA LL.B / LL.M Legal Studies",
    phone_number: "9930812940",
    year_of_study: "2nd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 4,
    retention_since_ai: "Slightly Decreased",
    forget_quickly_likert: 4,
    breadth_before_ai_likert: 4,
    depth_now_ai_likert: 4,
    struggle_independence: "Made me much less independent",
    personal_reflection: "",
    created_at: "2026-09-30T14:50:18.000Z"
  },
  {
    full_name: "Jeevan",
    course: "BA LL.B / LL.M Legal Studies",
    phone_number: "9820934182",
    year_of_study: "4th",
    ai_usage_frequency: "Weekly",
    recall_before_ai: 5,
    retention_since_ai: "Remained the Same",
    forget_quickly_likert: 3,
    breadth_before_ai_likert: 5,
    depth_now_ai_likert: 3,
    struggle_independence: "No change",
    personal_reflection: "",
    created_at: "2026-09-30T16:10:05.000Z"
  },
  {
    full_name: "Nitin",
    course: "B.Tech AI & Data Science",
    phone_number: "9873019284",
    year_of_study: "2nd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 4,
    retention_since_ai: "Significantly Decreased",
    forget_quickly_likert: 5,
    breadth_before_ai_likert: 4,
    depth_now_ai_likert: 5,
    struggle_independence: "Made me much less independent",
    personal_reflection: "tend to forget syntax without autocomplete now",
    created_at: "2026-10-01T09:20:40.000Z"
  },
  {
    full_name: "Vineeth",
    course: "B.Tech AI & Data Science",
    phone_number: "9940182930",
    year_of_study: "3rd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 4,
    retention_since_ai: "Slightly Decreased",
    forget_quickly_likert: 4,
    breadth_before_ai_likert: 4,
    depth_now_ai_likert: 4,
    struggle_independence: "Made me much less independent",
    personal_reflection: "",
    created_at: "2026-10-01T10:45:15.000Z"
  },
  {
    full_name: "Akshay",
    course: "B.Tech AI & Data Science",
    phone_number: "9848019234",
    year_of_study: "2nd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 3,
    retention_since_ai: "Slightly Decreased",
    forget_quickly_likert: 4,
    breadth_before_ai_likert: 3,
    depth_now_ai_likert: 4,
    struggle_independence: "Made me much less independent",
    personal_reflection: "",
    created_at: "2026-10-01T12:00:22.000Z"
  },
  {
    full_name: "John",
    course: "B.Tech AI & Data Science",
    phone_number: "9823091823",
    year_of_study: "1st",
    ai_usage_frequency: "Daily",
    recall_before_ai: 3,
    retention_since_ai: "Remained the Same",
    forget_quickly_likert: 4,
    breadth_before_ai_likert: 4,
    depth_now_ai_likert: 4,
    struggle_independence: "No change",
    personal_reflection: "makes understanding complex algorithms easier",
    created_at: "2026-10-01T14:15:30.000Z"
  },
  {
    full_name: "Akhil",
    course: "B.Tech AI & Data Science",
    phone_number: "9890182390",
    year_of_study: "3rd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 4,
    retention_since_ai: "Slightly Decreased",
    forget_quickly_likert: 4,
    breadth_before_ai_likert: 4,
    depth_now_ai_likert: 4,
    struggle_independence: "Made me much less independent",
    personal_reflection: "",
    created_at: "2026-10-01T15:35:45.000Z"
  },
  {
    full_name: "Adarsh",
    course: "B.Tech AI & Data Science",
    phone_number: "9765019283",
    year_of_study: "2nd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 4,
    retention_since_ai: "Slightly Decreased",
    forget_quickly_likert: 4,
    breadth_before_ai_likert: 3,
    depth_now_ai_likert: 4,
    struggle_independence: "Made me much less independent",
    personal_reflection: "",
    created_at: "2026-10-01T17:10:00.000Z"
  },
  {
    full_name: "Manya",
    course: "B.Tech Computer Science & Engineering",
    phone_number: "9810928301",
    year_of_study: "2nd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 3,
    retention_since_ai: "Slightly Decreased",
    forget_quickly_likert: 4,
    breadth_before_ai_likert: 4,
    depth_now_ai_likert: 4,
    struggle_independence: "Made me much less independent",
    personal_reflection: "saves a lot of time during exams prep",
    created_at: "2026-10-02T09:12:30.000Z"
  },
  {
    full_name: "Varshisth",
    course: "B.Sc Pure Sciences",
    phone_number: "9872019482",
    year_of_study: "1st",
    ai_usage_frequency: "Weekly",
    recall_before_ai: 3,
    retention_since_ai: "Remained the Same",
    forget_quickly_likert: 3,
    breadth_before_ai_likert: 4,
    depth_now_ai_likert: 3,
    struggle_independence: "No change",
    personal_reflection: "",
    created_at: "2026-10-02T10:30:44.000Z"
  },
  {
    full_name: "Darshini",
    course: "B.Sc Pure Sciences",
    phone_number: "9911029384",
    year_of_study: "3rd",
    ai_usage_frequency: "Weekly",
    recall_before_ai: 4,
    retention_since_ai: "Remained the Same",
    forget_quickly_likert: 3,
    breadth_before_ai_likert: 4,
    depth_now_ai_likert: 3,
    struggle_independence: "No change",
    personal_reflection: "",
    created_at: "2026-10-02T11:45:12.000Z"
  },
  {
    full_name: "Samridhi",
    course: "BBA Business Administration",
    phone_number: "9841092834",
    year_of_study: "2nd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 4,
    retention_since_ai: "Slightly Decreased",
    forget_quickly_likert: 4,
    breadth_before_ai_likert: 3,
    depth_now_ai_likert: 4,
    struggle_independence: "Made me much less independent",
    personal_reflection: "",
    created_at: "2026-10-02T13:20:19.000Z"
  },
  {
    full_name: "Himesh",
    course: "BBA Business Administration",
    phone_number: "9822019483",
    year_of_study: "3rd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 3,
    retention_since_ai: "Slightly Decreased",
    forget_quickly_likert: 4,
    breadth_before_ai_likert: 4,
    depth_now_ai_likert: 4,
    struggle_independence: "Made me much less independent",
    personal_reflection: "good for quick business report structure",
    created_at: "2026-10-02T15:05:00.000Z"
  },
  {
    full_name: "Himesh Sura",
    course: "BBA Business Administration",
    phone_number: "9831092843",
    year_of_study: "3rd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 4,
    retention_since_ai: "Slightly Decreased",
    forget_quickly_likert: 4,
    breadth_before_ai_likert: 4,
    depth_now_ai_likert: 4,
    struggle_independence: "Made me much less independent",
    personal_reflection: "",
    created_at: "2026-10-02T16:40:22.000Z"
  },
  {
    full_name: "Stephen",
    course: "B.Tech AI & Data Science",
    phone_number: "9845109283",
    year_of_study: "2nd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 4,
    retention_since_ai: "Significantly Decreased",
    forget_quickly_likert: 5,
    breadth_before_ai_likert: 4,
    depth_now_ai_likert: 5,
    struggle_independence: "Made me much less independent",
    personal_reflection: "",
    created_at: "2026-10-03T09:15:33.000Z"
  },
  {
    full_name: "Komal",
    course: "B.Tech AI & Data Science",
    phone_number: "9921094820",
    year_of_study: "3rd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 3,
    retention_since_ai: "Slightly Decreased",
    forget_quickly_likert: 4,
    breadth_before_ai_likert: 3,
    depth_now_ai_likert: 4,
    struggle_independence: "Made me much less independent",
    personal_reflection: "very helpful for completing code on time",
    created_at: "2026-10-03T10:50:11.000Z"
  },
  {
    full_name: "Sahasra Miryala",
    course: "B.Tech AI & Data Science",
    phone_number: "9870192840",
    year_of_study: "2nd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 4,
    retention_since_ai: "Slightly Decreased",
    forget_quickly_likert: 4,
    breadth_before_ai_likert: 4,
    depth_now_ai_likert: 4,
    struggle_independence: "Made me much less independent",
    personal_reflection: "",
    created_at: "2026-10-03T12:10:44.000Z"
  },
  {
    full_name: "Sahasra Reddy",
    course: "B.Tech AI & Data Science",
    phone_number: "9849018294",
    year_of_study: "2nd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 4,
    retention_since_ai: "Slightly Decreased",
    forget_quickly_likert: 4,
    breadth_before_ai_likert: 4,
    depth_now_ai_likert: 4,
    struggle_independence: "Made me much less independent",
    personal_reflection: "",
    created_at: "2026-10-03T14:35:19.000Z"
  },
  {
    full_name: "Vanshika",
    course: "B.Tech Computer Science & Engineering",
    phone_number: "9818029384",
    year_of_study: "1st",
    ai_usage_frequency: "Daily",
    recall_before_ai: 3,
    retention_since_ai: "Remained the Same",
    forget_quickly_likert: 3,
    breadth_before_ai_likert: 4,
    depth_now_ai_likert: 3,
    struggle_independence: "No change",
    personal_reflection: "",
    created_at: "2026-10-03T16:15:00.000Z"
  },
  {
    full_name: "Hansitha",
    course: "B.Tech Computer Science & Engineering",
    phone_number: "9717019284",
    year_of_study: "2nd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 4,
    retention_since_ai: "Significantly Decreased",
    forget_quickly_likert: 5,
    breadth_before_ai_likert: 4,
    depth_now_ai_likert: 5,
    struggle_independence: "Made me much less independent",
    personal_reflection: "relying on it a bit too much lately",
    created_at: "2026-10-04T09:40:22.000Z"
  },
  {
    full_name: "Sai Ganesh",
    course: "B.Tech Computer Science & Engineering",
    phone_number: "9848109283",
    year_of_study: "3rd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 4,
    retention_since_ai: "Slightly Decreased",
    forget_quickly_likert: 4,
    breadth_before_ai_likert: 5,
    depth_now_ai_likert: 4,
    struggle_independence: "Made me much less independent",
    personal_reflection: "",
    created_at: "2026-10-04T11:20:10.000Z"
  },
  {
    full_name: "Vaishna",
    course: "BBA Business Administration",
    phone_number: "9884019283",
    year_of_study: "1st",
    ai_usage_frequency: "Weekly",
    recall_before_ai: 3,
    retention_since_ai: "Remained the Same",
    forget_quickly_likert: 3,
    breadth_before_ai_likert: 3,
    depth_now_ai_likert: 3,
    struggle_independence: "No change",
    personal_reflection: "",
    created_at: "2026-10-04T13:05:40.000Z"
  },
  {
    full_name: "Siddharth",
    course: "B.Tech Computer Science & Engineering",
    phone_number: "9820194820",
    year_of_study: "4th",
    ai_usage_frequency: "Weekly",
    recall_before_ai: 4,
    retention_since_ai: "Remained the Same",
    forget_quickly_likert: 3,
    breadth_before_ai_likert: 5,
    depth_now_ai_likert: 3,
    struggle_independence: "No change",
    personal_reflection: "",
    created_at: "2026-10-04T15:20:18.000Z"
  },
  {
    full_name: "Rian",
    course: "B.Tech Computer Science & Engineering",
    phone_number: "9830192840",
    year_of_study: "2nd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 3,
    retention_since_ai: "Slightly Decreased",
    forget_quickly_likert: 4,
    breadth_before_ai_likert: 4,
    depth_now_ai_likert: 4,
    struggle_independence: "Made me much less independent",
    personal_reflection: "helps solve errors when stackoverflow fails",
    created_at: "2026-10-04T17:15:25.000Z"
  },
  {
    full_name: "Rohan",
    course: "B.Tech AI & Data Science",
    phone_number: "9876019284",
    year_of_study: "3rd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 4,
    retention_since_ai: "Significantly Decreased",
    forget_quickly_likert: 5,
    breadth_before_ai_likert: 4,
    depth_now_ai_likert: 5,
    struggle_independence: "Made me much less independent",
    personal_reflection: "",
    created_at: "2026-10-05T09:30:12.000Z"
  },
  {
    full_name: "Sansitha",
    course: "B.Tech AI & Data Science",
    phone_number: "9840192849",
    year_of_study: "2nd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 4,
    retention_since_ai: "Slightly Decreased",
    forget_quickly_likert: 4,
    breadth_before_ai_likert: 4,
    depth_now_ai_likert: 4,
    struggle_independence: "Made me much less independent",
    personal_reflection: "",
    created_at: "2026-10-05T11:05:44.000Z"
  },
  {
    full_name: "Yashwin",
    course: "B.Tech AI & Data Science",
    phone_number: "9910192840",
    year_of_study: "2nd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 4,
    retention_since_ai: "Slightly Decreased",
    forget_quickly_likert: 4,
    breadth_before_ai_likert: 4,
    depth_now_ai_likert: 4,
    struggle_independence: "Made me much less independent",
    personal_reflection: "",
    created_at: "2026-10-05T12:50:30.000Z"
  },
  {
    full_name: "Dhruv",
    course: "BBA Business Administration",
    phone_number: "9819019283",
    year_of_study: "2nd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 4,
    retention_since_ai: "Slightly Decreased",
    forget_quickly_likert: 4,
    breadth_before_ai_likert: 4,
    depth_now_ai_likert: 4,
    struggle_independence: "Made me much less independent",
    personal_reflection: "great for summarizing long articles",
    created_at: "2026-10-05T14:40:15.000Z"
  },
  {
    full_name: "Shailesh",
    course: "B.Tech AI & Data Science",
    phone_number: "9821092840",
    year_of_study: "3rd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 4,
    retention_since_ai: "Significantly Decreased",
    forget_quickly_likert: 5,
    breadth_before_ai_likert: 4,
    depth_now_ai_likert: 5,
    struggle_independence: "Made me much less independent",
    personal_reflection: "",
    created_at: "2026-10-05T16:20:00.000Z"
  },
  {
    full_name: "Ritwik",
    course: "B.Tech Computer Science & Engineering",
    phone_number: "9769019284",
    year_of_study: "3rd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 3,
    retention_since_ai: "Slightly Decreased",
    forget_quickly_likert: 4,
    breadth_before_ai_likert: 4,
    depth_now_ai_likert: 4,
    struggle_independence: "Made me much less independent",
    personal_reflection: "",
    created_at: "2026-10-06T09:15:45.000Z"
  },
  {
    full_name: "Aishwarya",
    course: "B.Tech AI & Data Science",
    phone_number: "9833019284",
    year_of_study: "2nd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 4,
    retention_since_ai: "Slightly Decreased",
    forget_quickly_likert: 4,
    breadth_before_ai_likert: 4,
    depth_now_ai_likert: 4,
    struggle_independence: "Made me much less independent",
    personal_reflection: "",
    created_at: "2026-10-06T11:00:20.000Z"
  },
  {
    full_name: "Ananya",
    course: "B.Tech Computer Science & Engineering",
    phone_number: "9920019284",
    year_of_study: "4th",
    ai_usage_frequency: "Daily",
    recall_before_ai: 4,
    retention_since_ai: "Slightly Decreased",
    forget_quickly_likert: 4,
    breadth_before_ai_likert: 5,
    depth_now_ai_likert: 4,
    struggle_independence: "Made me much less independent",
    personal_reflection: "dont memorize boilerplates anymore",
    created_at: "2026-10-06T13:25:10.000Z"
  },
  {
    full_name: "Saras",
    course: "BA LL.B / LL.M Legal Studies",
    phone_number: "9867019284",
    year_of_study: "3rd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 4,
    retention_since_ai: "Slightly Decreased",
    forget_quickly_likert: 4,
    breadth_before_ai_likert: 5,
    depth_now_ai_likert: 4,
    struggle_independence: "Made me much less independent",
    personal_reflection: "",
    created_at: "2026-10-06T15:10:00.000Z"
  },
  {
    full_name: "Shreeka",
    course: "B.Tech Computer Science & Engineering",
    phone_number: "9702019284",
    year_of_study: "1st",
    ai_usage_frequency: "Weekly",
    recall_before_ai: 3,
    retention_since_ai: "Remained the Same",
    forget_quickly_likert: 3,
    breadth_before_ai_likert: 4,
    depth_now_ai_likert: 3,
    struggle_independence: "No change",
    personal_reflection: "",
    created_at: "2026-10-06T16:45:30.000Z"
  },
  {
    full_name: "Chris",
    course: "BBA Business Administration",
    phone_number: "9849019285",
    year_of_study: "2nd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 3,
    retention_since_ai: "Slightly Decreased",
    forget_quickly_likert: 4,
    breadth_before_ai_likert: 3,
    depth_now_ai_likert: 4,
    struggle_independence: "Made me much less independent",
    personal_reflection: "",
    created_at: "2026-10-07T10:15:20.000Z"
  },
  {
    full_name: "Madhurima",
    course: "B.Tech Computer Science & Engineering",
    phone_number: "9811019284",
    year_of_study: "3rd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 4,
    retention_since_ai: "Slightly Decreased",
    forget_quickly_likert: 4,
    breadth_before_ai_likert: 4,
    depth_now_ai_likert: 4,
    struggle_independence: "Made me much less independent",
    personal_reflection: "saves time on theory questions",
    created_at: "2026-10-07T12:40:11.000Z"
  },
  {
    full_name: "Yogitha",
    course: "B.Tech Computer Science & Engineering",
    phone_number: "9930019284",
    year_of_study: "2nd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 4,
    retention_since_ai: "Slightly Decreased",
    forget_quickly_likert: 4,
    breadth_before_ai_likert: 4,
    depth_now_ai_likert: 4,
    struggle_independence: "Made me much less independent",
    personal_reflection: "",
    created_at: "2026-10-07T14:20:45.000Z"
  },
  {
    full_name: "Tiasha",
    course: "B.Tech Computer Science & Engineering",
    phone_number: "9820019284",
    year_of_study: "2nd",
    ai_usage_frequency: "Daily",
    recall_before_ai: 3,
    retention_since_ai: "Slightly Decreased",
    forget_quickly_likert: 4,
    breadth_before_ai_likert: 3,
    depth_now_ai_likert: 4,
    struggle_independence: "Made me much less independent",
    personal_reflection: "",
    created_at: "2026-10-07T16:05:00.000Z"
  }
];

module.exports = seedResponses;
